version: '3.9'
services:
  # services srv1,srv2,srv3 innodb cluster MySQL
  srv1:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_replica_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--host-cache-size=0","--skip-name-resolve", "--authentication_policy=mysql_native_password","--binlog_transaction_dependency_tracking=WRITESET"]
    volumes:
      - "dbData_srv1:/var/lib/mysql"
    deploy: 
      placement:
        constraints:
          - node.hostname==ATVVO
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.2.131:24224
        tag: MySQL_srv1
  srv2:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server
    command: ["mysqld","--server_id=2","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_replica_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--host-cache-size=0","--skip-name-resolve", "--authentication_policy=mysql_native_password","--binlog_transaction_dependency_tracking=WRITESET"]
    ports:
      - "3302:3306"
    volumes:
      - "dbData_srv2:/var/lib/mysql"
    deploy: 
      placement:
        constraints:
          - node.hostname==srv1
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.2.131:24224
        tag: MySQL_srv2
  srv3:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server
    command: ["mysqld","--server_id=3","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_replica_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--host-cache-size=0","--skip-name-resolve", "--authentication_policy=mysql_native_password","--binlog_transaction_dependency_tracking=WRITESET"]
    ports:
      - "3303:3306"
    volumes:
      - "dbData_srv3:/var/lib/mysql"
    restart: always
    deploy: 
      placement:
        constraints:
          - node.hostname==srv2
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.2.131:24224
        tag: MySQL_srv3
  router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    deploy: 
      placement:
        constraints:
          - node.hostname==ATVVO
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: MySQL_router
  wordpress:
    image: wordpress:php8.1-fpm 
    restart: always
    environment:
      WORDPRESS_DB_HOST: router:6446
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mysql
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - "data_html:/var/www/html"
    ports:
      - 9000:9000
    deploy: 
      placement:
        constraints:
          - node.hostname==ATVVO
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: wordpress
  nginx:
    image: kazaych/nginx_wp:1.2
    ports:
      - 8022:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - data_html:/var/www/html
    deploy: 
      placement:
        constraints:
          - node.hostname==ATVVO
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "nginx"

volumes:
  dbData_srv1:
  dbData_srv2:
  dbData_srv3:
  data_html:
    
      
    

