version: '3'
services:
  srv1:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_replica_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--host-cache-size=0","--skip-name-resolve", "--authentication_policy=mysql_native_password","--binlog_transaction_dependency_tracking=WRITESET"]
    volumes:
      - ./mysql_srv1:/var/lib/mysql
    restart: always
  srv2:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server
    command: ["mysqld","--server_id=2","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_replica_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--host-cache-size=0","--skip-name-resolve", "--authentication_policy=mysql_native_password","--binlog_transaction_dependency_tracking=WRITESET"]
    ports:
      - "3302:3306"
    volumes:
      - ./mysql_srv2:/var/lib/mysql
    restart: always
  srv3:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server
    command: ["mysqld","--server_id=3","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_replica_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--host-cache-size=0","--skip-name-resolve", "--authentication_policy=mysql_native_password","--binlog_transaction_dependency_tracking=WRITESET"]
    ports:
      - "3303:3306"
    volumes:
      - ./mysql_srv3:/var/lib/mysql
    restart: always
  router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    depends_on:
      srv1:
        condition: service_healthy
      srv2:
        condition: service_healthy
      srv3:
        condition: service_healthy
    restart: on-failure
  mysql-shell:
    image: kazaych/mysqlsh:1.2
    depends_on:
      srv1:
        condition: service_healthy
      srv2:
        condition: service_healthy
      srv3:
        condition: service_healthy
  wordpress:
    image: wordpress:php8.1-fpm 
    restart: always
    environment:
      WORDPRESS_DB_HOST: router:6446
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mysql
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./data/html:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      srv1:
        condition: service_healthy
      srv2:
        condition: service_healthy
      srv3:
        condition: service_healthy
  nginx:
    image: nginx
    restart: always
    depends_on:
      srv1:
        condition: service_healthy
      srv2:
        condition: service_healthy
      srv3:
        condition: service_healthy
    ports:
      - 8022:80
    volumes:
      - ./nginx_log:/var/log/nginx
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
networks:
  default:
    name: "Otus_project"
