version: '3.9'
services:
  fluent-bit:
    image: fluent/fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - type: volume
        source: fluent_conf
        target: /fluent-bit/etc
        volume:
          nocopy: true
    deploy: 
      replicas: 3
      restart_policy:
        condition: on-failure
  elasticsearch:
    image: elasticsearch:7.17.3
    environment:
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    deploy: 
      placement:
        constraints:
          - node.hostname==ATVVO
      replicas: 1
      restart_policy:
        condition: on-failure
  kibana:
    image: kibana:7.17.3
    ports:
      - "5601:5601"
    deploy: 
      placement:
        constraints:
          - node.hostname==ATVVO
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  fluent_conf:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.2.131,nolock,soft,rw
      device: ":/home/kz/OTUS_PROJ/Loging/fluent-bit"


      